set(CARGO_COMPILER "cargo")
set(CARGO_COMPILER_RELEASE "--release")
set(CARGO_COMPILER_DEBUG "")
set(CARGO_COMPILER_DOC "doc")
set(CARGO_COMPILER_SET_TARGET "--target")
set(CARGO_OUTPUT "--artifact-dir")
set(CARGO_BASE_COMPILER "rustc")